### ISSUE TITLE
Spontaneously rejoined to a room which I left, and now can't interact with

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#1940]
We have seen a number of reports of the following:

* user leaves a room
* at some point later, their client starts showing it again
* Attempts to leave get "Not a known room" or "Room does not exist"
* Attempts to send a message get `User @foo:bar not in room !baz:bleh`

**Comment by richvdh** [comment]
I think the cause of this is the state resets caused by #1935. Possibly, another HS ends up with its state wound back to a point at which you were a member of the room, and starts sending events with prev_events which predate your departure. Your own HS then gets confused and starts telling clients that you are in the room (when you really aren't).

**Comment by enckse** [comment]
Just for an additional data point:
* I've definitely been hit by #1629 at least 2 or times over the weekend 
* and this issue itself (rejoined to Matrix-HQ oddly enough)

**Comment by richvdh** [comment]
> I've definitely been hit by #1629 at least 2 or 3 times over the weekend
> and this issue itself (rejoined to Matrix-HQ oddly enough)

This and #1629 are the same thing as far as I'm concerned, so this doesn't make much sense. Please could you make yourself known on Matrix and explain what you're seeing?

**Comment by enckse** [comment]
I can make myself known but I am/was agreeing with you (sorry if that wasn't clear before).

**Comment by richvdh** [comment]
this was fixed for `@boli:boli.rocks` by re-inviting him, after which he was able to reject the invite and resume normal service.

**Comment by rubo77** [comment]
My synapse thought, I was in #matrix-dev, although I wasn't there. My database had this entry:

```
select * FROM current_state_events WHERE room_id like '%XqBunHwQIXUiqCaoxq:matrix.org
' and state_key = '@rubo77:mydomain';                      
               event_id                |            room_id             |     type      |        state_key
---------------------------------------+--------------------------------+---------------+--------------------------
 $14713765517956PLlfc:mydomain | !XqBunHwQIXUiqCaoxq:matrix.org | m.room.member | @rubo77:mydomain    
```

I could fix it by deleting the current state with:

    delete FROM current_state_events WHERE room_id = '!id:matrix.org' and state_key = '@rubo77:mydomain';

Then I could rejoin the room and everything is back to normal

**Comment by ChazyTheBest** [comment]
I got a similar situation:

- Create a new room
- Leave
- Try to join again
- Internal server error (M_UNKNOWN)

With both the web interface and riot.im. But the room still exists, and I can see the history.

**Comment by richvdh** [comment]
@ChazyTheBest @rubo77 they sound like different issues. Please open new issues.

**Comment by richvdh** [comment]
Given that #1935 has been fixed, I'm going to close this. #1940 remains as an open issue. If people continue to find themselves spuriously rejoined to rooms, please open new issues - it's easier to close as duplicates than it is to unpick reports of several problems on the same issue.
