### ISSUE TITLE
Unable to join #matrix-architecture:matrix.org

### ISSUE THREAD

**Issue by Ekleog** [matrix-org/synapse#3036]
### Description and steps to reproduce

Trying to join `#matrix-architecture:matrix.org` fails with an internal server error, with the following in the logs (don't know whether the timeouts are related, but hey):
```
Mar 27 23:24:43 grym synapse[19154]: twisted: [] Timing out client: IPv4Address(TCP, '162.220.112.110', 27637)
Mar 27 23:24:43 grym synapse[19154]: twisted: [] Timing out client: IPv4Address(TCP, '88.97.97.212', 34996)
Mar 27 23:24:44 grym synapse[19154]: synapse.federation.federation_client: [POST-262711] Failed to send_join via matrix.org: 'NoneType' object is not callable
                                     Traceback (most recent call last):
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/federation/federation_client.py", line 589, in send_join
                                         outlier=True,
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/federation/federation_base.py", line 109, in _check_sigs_and_hash_and_fetch
                                         )).addErrback(unwrapFirstError)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
                                         current.result = callback(current.result, *args, **kw)
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/util/logcontext.py", line 289, in g
                                         res = f(res, *args, **kwargs)
                                     TypeError: 'NoneType' object is not callable
Mar 27 23:24:44 grym synapse[19154]: synapse.util.async: [POST-262711] Releasing linearizer lock 'member' for key ('!fILrmqIZQfJcrUiBRk:matrix.org',)
Mar 27 23:24:44 grym synapse[19154]: synapse.http.server: [POST-262711] Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7f59000aeb90>: <SynapseRequest at 0x7f58fe768050 method=POST uri=/_matrix/client/r0/join/%23matrix-architecture:matrix.org?access_token=<redacted> clientproto=HTTP/1.1 site=8448>
                                     Traceback (most recent call last):
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
                                         yield request_handler(self, request, request_metrics)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/http/server.py", line 255, in _async_render
                                         callback_return = yield callback(request, **kwargs)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/rest/client/v1/room.py", line 270, in on_POST
                                         third_party_signed=content.get("third_party_signed", None),
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/handlers/room_member.py", line 168, in update_membership
                                         content=content,
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/handlers/room_member.py", line 267, in _update_membership
                                         remote_room_hosts, room_id, target, content
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/handlers/room_member.py", line 139, in remote_join
                                         content,
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/handlers/federation.py", line 898, in do_invite_join
                                         ret = yield self.replication_layer.send_join(target_hosts, event)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/9w7q4wrkg4q9jxfdj7xv69wm0838qpq7-python2.7-Twisted-17.5.0/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/42mc2svldn7rs7n90ws1ymh25gzszvsj-matrix-synapse-0.22.1/lib/python2.7/site-packages/synapse/federation/federation_client.py", line 637, in send_join
                                         raise RuntimeError("Failed to send to any server.")
                                     RuntimeError: Failed to send to any server.
Mar 27 23:24:44 grym synapse[19154]: synapse.access.https.8448: [POST-262711] 127.0.0.1 - 8448 - {@leo:gaspard.ninja} Processed request: 6042ms (37ms, 1ms) (0ms/4) 55B 500 "POST /_matrix/client/r0/join/%23matrix-architecture:matrix.org?access_token=<redacted> HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
Mar 27 23:24:44 grym synapse[19154]: signedjson.sign: [] Error verifying signature
                                     Traceback (most recent call last):
                                       File "/nix/store/dck17lllvgjhrdzd1344j1w9yw1cajjv-python2.7-signedjson-1.0.0/lib/python2.7/site-packages/signedjson/sign.py", line 121, in verify_signed_json
                                         verify_key.verify(message, signature)
                                       File "/nix/store/lkw893a8i9sqp57b6dy0n1irlrihvpsr-python2.7-pynacl-0.3.0/lib/python2.7/site-packages/nacl/signing.py", line 100, in verify
                                         return nacl.bindings.crypto_sign_open(smessage, self._key)
                                       File "/nix/store/lkw893a8i9sqp57b6dy0n1irlrihvpsr-python2.7-pynacl-0.3.0/lib/python2.7/site-packages/nacl/bindings/crypto_sign.py", line 100, in crypto_sign_open
                                         raise BadSignatureError("Signature was forged or corrupt")
                                     BadSignatureError: Signature was forged or corrupt
Mar 27 23:24:44 grym synapse[19154]: synapse.federation.federation_base: [POST-262711] Signature check failed for $Cqh67TG9cdki4MkgzwPJG1XUwhbHxvXkfQbfci2AKh2S:zemos.net
Mar 27 23:24:44 grym synapse[19154]: synapse.federation.federation_client: [POST-262711] Not retrying server zemos.net.
Mar 27 23:24:44 grym synapse[19154]: synapse.federation.federation_base: [POST-262711] Failed to find copy of $Cqh67TG9cdki4MkgzwPJG1XUwhbHxvXkfQbfci2AKh2S:zemos.net with valid signature
[and then still some stuff on the same second but that doesn't look directly related to the issue at hand]
```

### Version information

- **Homeserver**: On my own homeserver

If not matrix.org:
- **Version**:   The given command line (`curl -v https://[myhs]/_matrix/client/versions 2>&1 | grep 'Server:') doesn't return anything, but NixOS tells me it's 0.22.1.
- **Install method**: package manager
- **Platform**:      NixOS on bare metal

**Comment by Ekleog** [comment]
Also, it looks like after some time the join actually succeeded, so… guess there's still something wrong here, but…

**Comment by neilisfragile** [comment]
Given the age of v0.22.1 am tempted to assume this has been fixed in a later version - can you reproduce with v0.27.2?

**Comment by Ekleog** [comment]
Unfortunately the join eventually succeeded, so I can't really try reproducing. Given there was no issue with the "Signature was forged or corrupt" message I assumed it wasn't fixed since then, but will close if you think I'm mistaken and/or this would require too much investigation compared to the likelihood of this being a still-alive bug!

**Comment by neilisfragile** [comment]
I think on balance I'd like to close, simply because it is not something I am aware of as a general issue with recent releases. Thank you for raising though - and if you can I really encourage you to upgrade lots of good stuff in recent releases.
