### ISSUE TITLE
pyjwt missing from debian distribution

### ISSUE THREAD

**Issue by oliverjanik** [matrix-org/synapse#3793]
1. Install the official matrix debian package on ubuntu
1. configure jwt_config section in homeserver.yaml
1. Generate JWT and do a POST /client/r0/login with type `m.login.jwt`

Blows up on `import jwt`

```
2018-09-04 07:01:22,850 - synapse.http.server - 101 - ERROR - POST-12- Failed handle request via <function _async_render at 0x7fe44633da28>: <SynapseRequest at 0x7fe43fbe55a8 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site=8008>: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/login.py", line 145, in on_POST
    result = yield self.do_jwt_login(login_submission)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/login.py", line 278, in do_jwt_login
    import jwt
exceptions.ImportError: No module named jwt
```

**Comment by richvdh** [comment]
> Why is not installed by default?

because most people don't use jwt auth.

**Comment by oliverjanik** [comment]
That is ok for source distriubution. 

But for a debian package or docker image? Do expect people modify those to get it running?

**Comment by richvdh** [comment]
I think it's reasonable to have to install extra debian packages to get exotic auth integrations working. It's unsatisfactory that this isn't clearly documented and that the failure mode isn't clearer.

**Comment by hawkowl** [comment]
Fixed in #3824

**Comment by oliverjanik** [comment]
Please reopen the instructions are wrong now that the debian package uses venv:

Previous systemd unit file:
```
[Unit]
Description=Synapse Matrix homeserver

[Service]
Type=simple
User=matrix-synapse
WorkingDirectory=/var/lib/matrix-synapse
EnvironmentFile=/etc/default/matrix-synapse
ExecStartPre=/usr/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --generate-keys
ExecStart=/usr/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
```

Latest Unit file:
```
[Unit]
Description=Synapse Matrix homeserver

[Service]
Type=simple
User=matrix-synapse
WorkingDirectory=/var/lib/matrix-synapse
EnvironmentFile=/etc/default/matrix-synapse
ExecStartPre=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --generate-keys
ExecStart=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
```

So if i install global python-jwt  it still does not work because matrix uses venv'ed python.
