### ISSUE TITLE
Notification settings not transferred on room upgrade

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#5295]
Just had an instance of notification settings not transferring on room upgrade. Note to self to check hs logs.

https://github.com/vector-im/riot-web/issues/9905

**Comment by turt2live** [comment]
What happened to https://github.com/matrix-org/synapse/issues/4597 ?

**Comment by anoadragon453** [comment]
There seems to be an edge case.

**Comment by hawkowl** [comment]
Fixed by #6155

**Comment by turt2live** [comment]
This is empirically still happening to some people: https://github.com/vector-im/riot-web/issues/11803
